-- AlterTable
ALTER TABLE `farsi_entries` MODIFY `type` ENUM('NOUN', 'VERB', 'ADJECTIVE', 'ADVERB', 'PRONOUN', 'QUESTION_WORD', 'PREPOSITION', 'CONJUNCTION', 'NUMBER', 'PHRASE', 'IDIOM', 'OTHER') NULL;
