-- AlterTable
ALTER TABLE `farsi_entries` MODIFY `type` ENUM('NOUN', 'VERB', 'ADJECTIVE', 'ADVERB', 'PRONOUN', 'QUESTION_WORD', 'PREPOSITION', 'CONJUNCTION', 'PARTICLE', 'NUMBER', 'PHRASE', 'IDIOM', 'LETTER', 'OTHER') NULL;
